"""Regenerate tests/golden_example1.json from the committed LONGBASE.

The strict validation test (tests/test_validation.py) pins the example1 demo's
funds-rate / GDP deviations. Those numbers depend on the data vintage, so this
script recomputes them from whatever LONGBASE is currently committed and writes
them (plus the LONGBASE sha256) back to the golden JSON. The data-refresh
workflow runs it right after pulling a new LONGBASE, so an unattended data
update keeps the strict test consistent instead of going stale.

Run manually after any manual data/model bump:

    python scripts/regen_goldens.py
"""

from __future__ import annotations

import hashlib
import json
import pathlib
import sys

import matplotlib

matplotlib.use("Agg")

import pandas as pd  # noqa: E402

ROOT = pathlib.Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from frbus_shock.model import load_baseline, load_frbus  # noqa: E402
from frbus_shock.paths import LONGBASE_TXT  # noqa: E402

GOLDEN_PATH = ROOT / "tests" / "golden_example1.json"


def compute_goldens():
    """Reproduce demos/example1 and return (rff_bp, xgdp_pct) for 8 quarters."""
    frbus = load_frbus("var")
    data = load_baseline()
    start = pd.Period("2040Q1", freq="Q")
    end = start + 23
    data.loc[start:end, "dfpdbt"] = 0
    data.loc[start:end, "dfpsrp"] = 1
    with_adds = frbus.init_trac(start, end, data)
    with_adds.loc[start, "rffintay_aerr"] += 1
    sim = frbus.solve(start, end, with_adds)
    rff_bp = ((sim.loc[start:end, "rff"] - with_adds.loc[start:end, "rff"]) * 100).head(8)
    xgdp_pct = (
        (sim.loc[start:end, "xgdp"] / with_adds.loc[start:end, "xgdp"] - 1) * 100
    ).head(8)
    return [round(float(x), 4) for x in rff_bp], [round(float(x), 5) for x in xgdp_pct]


def main() -> int:
    rff_bp, xgdp_pct = compute_goldens()
    sha = hashlib.sha256(LONGBASE_TXT.read_bytes()).hexdigest()
    payload = {
        "description": (
            "Golden deviations for demos/example1 (100 bp rffintay_aerr shock, VAR "
            "expectations, 2040Q1), first 8 quarters. Regenerated by "
            "scripts/regen_goldens.py whenever LONGBASE is refreshed."
        ),
        "recipe": (
            "init_trac(2040Q1..+23) with dfpdbt=0, dfpsrp=1; "
            "rffintay_aerr += 1 at 2040Q1; solve"
        ),
        "vintage_sha256": sha,
        "rff_bp": rff_bp,
        "xgdp_pct": xgdp_pct,
    }
    GOLDEN_PATH.write_text(json.dumps(payload, indent=2) + "\n")
    print(json.dumps(payload, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
